# Generated by Django 5.2.8 on 2025-11-24 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glovo_app', '0003_alter_address_store_alter_contact_store_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='glovo_app.storemenu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='glovo_app.store'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='glovo_app.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glovo_app.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='glovo_app.category'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='storemenu',
            name='menu_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storemenu',
            name='menu_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storemenu',
            name='menu_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storemenu',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_menu', to='glovo_app.store'),
        ),
    ]
